name: forsaty
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core (Required)
  firebase_core: ^3.0.0

  # Firebase Services
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0

  # State Management
  flutter_bloc: ^8.1.2
  equatable: ^2.0.3

  # Icons
  cupertino_icons: ^1.0.8

  # For post IDs
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/Rectangle 11.png
    - assets/Rectangle 12.png
    - assets/logo 2.png
    - assets/Subtract.png
    - assets/Group.png

  fonts:
    - family: JosefinSans
      fonts:
        - asset: fonts/JosefinSans-VariableFont_wght.ttf
